import React, { useState } from 'react';
import { useAuth } from '../../hooks/useAuth';

export default function Login({ onLogin }) {
  const { login } = useAuth();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async event => { event.preventDefault(); if (!email || !password) return setError('Enter both your email address and password.'); setLoading(true); setError(''); try { await login(email, password); onLogin(); } catch (requestError) { setError(requestError.response?.data?.message || 'Sign-in failed. Please try again.'); } finally { setLoading(false); } };
  return <main className="login-page"><section className="login-panel"><div className="login-brand"><span className="login-mark">✓</span><span>Taskflow</span></div><div className="login-copy"><p className="eyebrow">WHATSAPP TASK MANAGER</p><h1>Your tasks,<br/><em>in focus.</em></h1><p>Capture important WhatsApp messages and turn them into a calm, organized day.</p><div className="login-feature"><span>✓</span> Never lose a deadline again</div><div className="login-feature"><span>✓</span> All the context, one click away</div></div></section><section className="login-form-area"><form className="login-card" onSubmit={submit}><div className="login-heading"><p className="eyebrow">WELCOME BACK</p><h2>Sign in to your workspace</h2><p>Enter your details to continue.</p></div>{error && <div className="login-error" role="alert">{error}</div>}<label>Email address<input type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="you@example.com" disabled={loading} autoComplete="username" /></label><label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} placeholder="Enter your password" disabled={loading} autoComplete="current-password" /></label><button className="login-submit" type="submit" disabled={loading}>{loading ? 'Signing in…' : 'Sign in to dashboard'} <span>→</span></button><p className="login-footnote">Your WhatsApp tasks stay private to your account.</p></form></section></main>;
}
